# Generated by Django 4.2.7 on 2024-04-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Telegram chat ID'),
        ),
    ]
