# Generated by Django 4.2.7 on 2024-04-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company name')),
                ('inn', models.CharField(max_length=10, verbose_name='Company INN')),
                ('kpp', models.CharField(max_length=10, verbose_name='Company KPP')),
                ('address', models.CharField(max_length=100, verbose_name='Company Address')),
                ('amount', models.CharField(max_length=100, verbose_name='Company Amount')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
