# Generated by Django 4.2.7 on 2024-04-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='invoice_path'),
        ),
    ]
