# Generated by Django 4.2.7 on 2024-04-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='media/invoices/', verbose_name='invoice_path'),
        ),
    ]
